services:
  db:
    container_name: trec
    image: postgis/postgis:15-master
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /data/postgres
    ports:
      - "5438:5432"
    volumes:
      - postgis_data:/data/postgres
      - ../public/data/stop_features.geojson:/data/public/stop_features.geojson
      - ../public/data/hospitals.geojson:/data/public/hospitals.geojson
      # - ./11-create_tables.sql:/docker-entrypoint-initdb.d/11-create_tables.sql
      # - ./12-insert_initial_data.sql:/docker-entrypoint-initdb.d/12-insert_initial_data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d trec"]
      interval: 5s
      timeout: 5s
      retries: 5
  martin:
    image: ghcr.io/maplibre/martin:v0.13.0
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_DB}/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy


volumes:
  postgis_data: 
